name: chapter03
services:
  mariadb:
    image: mariadb:lts-ubi
    container_name: mariadb-service
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root_password_here
      MARIADB_DATABASE: my_database
      MARIADB_USER: my_user
      MARIADB_PASSWORD: my_password
    ports:
      - '127.0.0.1:3306:3306'
    restart: always

volumes:
  mariadb_data:
