name: chapter05
services:
  mariadb:
    image: mariadb:lts-ubi
    container_name: mariadb-service
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: YOUR_ROOT_PASSWORD
      MARIADB_DATABASE: cardb
      MARIADB_USER: cardb_user
      MARIADB_PASSWORD: YOUR_DB_PASSWORD
    ports:
      - '127.0.0.1:3306:3306'
    restart: always

volumes:
  mariadb_data:
